theme = 'mainroad'

baseURL = 'http://example.org/'
languageCode = 'ja-jp'
hasCJKLanguage = true
summaryLength = 120

[Author]
  name = "ひで"
  bio = "千葉でロボティクスを学んでいる大学生です。"
  avatar = "resource/penguin.jpg"

[Params]
  highlightColor = "#725889"
  title = "ひでのブログ"
  subtitle = "備忘録とかいろいろ"
  copyright = "hide4096"

[[Menus.main]]
  Name = "ホーム"
  URL = "/"

[[Menus.main]]
  Name = "カテゴリー"
  URL = "/categories/"

[[Menus.main]]
  Name = "タグ"
  URL = "/tags/"

[Params.sidebar]
  home = "right"
  list = "right"
  single = false
  widgets = ["search","recent","categories","taglist","social","twitter"]

[Params.widgets.social]
  twitter = "hide4096"
  github = "hide4096"
