theme = 'mainroad'

baseURL = 'https://hide4096.github.io/'
DefaultContentLanguage = "ja"
paginate = "10"
languageCode = 'ja-JP'
hasCJKLanguage = true
title = "ひでのブログ"

[Author]
  name = "ひで"
  bio = "千葉でロボティクスを学んでいる大学生です。"
  avatar = "static/penguin.jpg"

[Params]
  highlightColor = "#725889"
  description = "ひでのブログです。頑張って書きます。"
  copyright = "hide4096"
  toc = false
  pager = true
  readmore = false
  schema = true
  post_meta = ["date","categories"]
  dataformat = "1970-01-01"

[Params.logo]
  title = "ひでのブログ"
  subtitle = "備忘録とかいろいろ"

[[Menus.main]]
  Name = "ホーム"
  URL = "/"
  weight = 1

[[Menus.main]]
  Name = "カテゴリー"
  URL = "/categories/"
  weight = 2

[[Menus.main]]
  Name = "タグ"
  URL = "/tags/"
  weight = 3

[[Menus.main]]
  Name = "このブログについて"
  URL = "/about/"
  weight = 4

[Params.sidebar]
  home = "right"
  list = "right"
  single = "rightr"
  widgets = ["search","recent","categories","taglist","social","twitter"]

[Params.widgets.social]
  twitter = "hide4096"
  github = "hide4096"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
