theme = 'mainroad'

baseURL = 'http://example.org/'
DefaultContentLanguage = "ja"
languageCode = 'ja-JP'
hasCJKLanguage = true
summaryLength = 120

[Author]
  name = "ひで"
  bio = "千葉でロボティクスを学んでいる大学生です。"
  avatar = "resource/penguin.jpg"

[Params]
  highlightColor = "#725889"
  title = "ひでのブログ"
  description = "ひでのブログです。技術ネタが多いです。知らんけど"
  copyright = "hide4096"
  toc = false
  post_meta = ["date","categories"]
  dataformat = "1970-01-01"

[Params.logo]
  title = "ひでのブログ"
  subtitle = "備忘録とかいろいろ"

[[Menus.main]]
  Name = "ホーム"
  URL = "/"
  weight = 1

[[Menus.main]]
  Name = "カテゴリー"
  URL = "/categories/"
  weight = 2

[[Menus.main]]
  Name = "タグ"
  URL = "/tags/"
  weight = 3

[Params.sidebar]
  home = "right"
  list = "right"
  single = false
  widgets = ["search","recent","categories","taglist","social","twitter"]

[Params.widgets.social]
  twitter = "hide4096"
  github = "hide4096"
